### ISSUE TITLE
在缩放显示的设备上运行，画面会被切割，无法显示完整

### ISSUE THREAD

**Issue by zhongwcool** [tsingsee/EasyPlayer-RTMP-Win#3]
在缩放显示（比如高分辨率+显示放大125%）的设备上运行，高分辨率的画面会被切割，无法显示完整

**Comment by Tsingsee-Seven** [comment]
您好，我是青犀产品负责人秦吉伟，你可以叫我Seven，我们在安徽省合肥市高新区，我的电话联系方式为：18855112323。(同微信) 





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tsingsee/EasyPlayer-RTMP-Win"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月13日(星期四) 上午8:53
收件人:&nbsp;"tsingsee/EasyPlayer-RTMP-Win"<EasyPlayer-RTMP-Win@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[tsingsee/EasyPlayer-RTMP-Win] 在缩放显示的设备上运行，画面会被切割，无法显示完整 (#3)





 
在缩放显示（比如高分辨率+显示放大125%）的设备上运行，高分辨率的画面会被切割，无法显示完整
